import { ATTRIBUTES } from "./combat-model"
export const PRESET_CHECKS = [
  {
    id: "c1",
    name: "Percepção",
    attrs: ["ins", "dex"],
    desc: "Notar detalhes, movimentos sutis, armadilhas, emboscadas ou objetos escondidos.",
  },
  {
    id: "c2",
    name: "Investigação",
    attrs: ["ins", "wlp"],
    desc: "Reconstruir acontecimentos em uma cena, interpretar pistas e ligar informações.",
  },
  {
    id: "c3",
    name: "Empatia",
    attrs: ["ins", "wlp"],
    desc: "Ler emoções, identificar blefes, nervosismo e compreender as reais intenções de alguém.",
  },
  {
    id: "c4",
    name: "Avaliação",
    attrs: ["ins", "ins"],
    desc: "Estimar o valor financeiro de mercadorias, reconhecer antiguidades e identificar falsificações.",
  },
  {
    id: "c5",
    name: "Interrogatório",
    attrs: ["wlp", "ins"],
    desc: "Extrair informações de prisioneiros ou suspeitos através de pressão psicológica ou blefe tático.",
  },
  {
    id: "c6",
    name: "Sobrevivência Selvagem",
    attrs: ["ins", "mig"],
    desc: "Encontrar alimento, preparar abrigos rudimentares e prever tempestades ou perigos naturais.",
  },
  {
    id: "c7",
    name: "Rastreamento",
    attrs: ["ins", "dex"],
    desc: "Identificar e seguir pegadas, rastros de sangue e sinais de passagem de animais ou pessoas.",
  },
  {
    id: "c8",
    name: "Orientação",
    attrs: ["ins", "ins"],
    desc: "Ler mapas terrestres ou astrais, guiar o grupo e evitar que se percam durante viagens.",
  },
  {
    id: "c9",
    name: "Sobrevivência Urbana",
    attrs: ["ins", "wlp"],
    desc: "Encontrar rotas seguras em becos, localizar o mercado negro e entender as regras não ditas das ruas.",
  },
  {
    id: "c10",
    name: "Vigília",
    attrs: ["ins", "mig"],
    desc: "Manter-se alerta durante o turno de guarda, lutando contra o sono para proteger o grupo.",
  },
  {
    id: "c11",
    name: "Medicina",
    attrs: ["ins", "dex"],
    desc: "Realizar cirurgias de emergência, suturar feridas, estabilizar aliados e aplicar primeiros socorros.",
  },
  {
    id: "c12",
    name: "Botânica e Venenos",
    attrs: ["ins", "ins"],
    desc: "Identificar plantas seguras, extrair toxinas, fabricar antídotos naturais e unguentos.",
  },
  {
    id: "c13",
    name: "História e Cultura",
    attrs: ["ins", "ins"],
    desc: "Lembrar fatos antigos, reconhecer brasões de nobreza, leis locais e costumes regionais.",
  },
  {
    id: "c14",
    name: "Engenharia e Mecânica",
    attrs: ["ins", "dex"],
    desc: "Desarmar armadilhas complexas, compreender maquinários, relógios e construir engenhocas.",
  },
  {
    id: "c15",
    name: "Criptografia",
    attrs: ["ins", "wlp"],
    desc: "Decodificar mensagens secretas, traduzir dialetos mortos e resolver enigmas lógicos.",
  },
  {
    id: "c16",
    name: "Estratégia",
    attrs: ["wlp", "ins"],
    desc: "Planejar táticas de batalha, prever a movimentação inimiga e vencer jogos de tabuleiro.",
  },
  {
    id: "c17",
    name: "Furtividade",
    attrs: ["dex", "ins"],
    desc: "Esconder-se nas sombras, mover-se sem fazer ruído e infiltrar-se em áreas vigiadas.",
  },
  {
    id: "c18",
    name: "Prestidigitação",
    attrs: ["dex", "ins"],
    desc: "Bater carteiras, esconder itens pequenos nas mangas ou realizar truques de mãos rápidos.",
  },
  {
    id: "c19",
    name: "Arrombamento",
    attrs: ["dex", "ins"],
    desc: "Usar gazuas para abrir fechaduras de portas, baús ou destrancar algemas silenciosamente.",
  },
  {
    id: "c20",
    name: "Enganação",
    attrs: ["wlp", "dex"],
    desc: "Mentir de forma convincente, usar disfarces, forjar sotaques e improvisar histórias.",
  },
  {
    id: "c21",
    name: "Falsificação",
    attrs: ["dex", "ins"],
    desc: "Criar cópias exatas de documentos, assinaturas, selos oficiais e passaportes.",
  },
  {
    id: "c22",
    name: "Acrobacia",
    attrs: ["dex", "mig"],
    desc: "Saltar entre telhados, amortecer quedas, equilibrar-se em cordas e rolar durante o combate.",
  },
  {
    id: "c23",
    name: "Reflexos",
    attrs: ["dex", "ins"],
    desc: "Reagir a ataques surpresa, segurar objetos caindo ou acionar alavancas sob pressão extrema.",
  },
  {
    id: "c24",
    name: "Precisão",
    attrs: ["dex", "ins"],
    desc: "Fazer arremessos difíceis, atirar facas em alvos pequenos ou acertar pontos fracos.",
  },
  {
    id: "c25",
    name: "Condução",
    attrs: ["dex", "ins"],
    desc: "Manobrar carroças em alta velocidade, pilotar barcos ou montar a cavalo em terrenos difíceis.",
  },
  {
    id: "c26",
    name: "Contorcionismo",
    attrs: ["dex", "dex"],
    desc: "Escapar de amarras de corda, espremer-se em tubulações e passar por grades estreitas.",
  },
  {
    id: "c27",
    name: "Atletismo",
    attrs: ["mig", "dex"],
    desc: "Escalar paredões, nadar contra a correnteza, correr em disparada e empurrar pedras pesadas.",
  },
  {
    id: "c28",
    name: "Força Bruta",
    attrs: ["mig", "mig"],
    desc: "Quebrar portas de madeira, erguer pesos descomunais, dobrar barras de ferro e intimidar fisicamente.",
  },
  {
    id: "c29",
    name: "Resistência",
    attrs: ["mig", "wlp"],
    desc: "Suportar marchas forçadas, ignorar a dor crônica, resistir ao frio/calor e aguentar tortura.",
  },
  {
    id: "c30",
    name: "Fôlego",
    attrs: ["mig", "mig"],
    desc: "Prender a respiração por longos minutos debaixo d'água ou em ambientes com gás tóxico.",
  },
  {
    id: "c31",
    name: "Briga",
    attrs: ["mig", "dex"],
    desc: "Entrar em combate corpo a corpo desarmado, imobilizar adversários e aplicar chaves de braço.",
  },
  {
    id: "c32",
    name: "Diplomacia",
    attrs: ["wlp", "ins"],
    desc: "Convencer, apaziguar ânimos, negociar pagamentos justos e resolver conflitos sem violência.",
  },
  {
    id: "c33",
    name: "Intimidação",
    attrs: ["wlp", "mig"],
    desc: "Amedrontar usando tom de voz agressivo, ameaças verbais e postura corporal hostil.",
  },
  {
    id: "c34",
    name: "Liderança",
    attrs: ["wlp", "ins"],
    desc: "Inspirar coragem nos aliados, coordenar pessoas em pânico e dar ordens claras sob fogo inimigo.",
  },
  {
    id: "c35",
    name: "Etiqueta",
    attrs: ["wlp", "ins"],
    desc: "Portar-se em eventos da alta nobreza, usar os talheres certos e falar com a realeza sem ofender.",
  },
  {
    id: "c36",
    name: "Atuação",
    attrs: ["wlp", "dex"],
    desc: "Chamar a atenção de uma multidão, dançar, cantar ou atuar para criar uma distração perfeita.",
  },
  {
    id: "c37",
    name: "Trato com Animais",
    attrs: ["ins", "wlp"],
    desc: "Acalmar cães de guarda, adestrar montarias e entender o comportamento de feras selvagens.",
  },
  {
    id: "c38",
    name: "Foco e Vontade",
    attrs: ["wlp", "wlp"],
    desc: "Manter a mente fria diante do horror, resistir a provocações e focar em uma tarefa durante o caos.",
  },
  {
    id: "c39",
    name: "Ofícios e Forja",
    attrs: ["dex", "ins"],
    desc: "Consertar armaduras rachadas, afiar lâminas, costurar couro e criar ferramentas improvisadas.",
  },
  {
    id: "c40",
    name: "Culinária",
    attrs: ["ins", "dex"],
    desc: "Limpar e preparar carne de caça, racionar mantimentos e cozinhar refeições que recuperam o ânimo.",
  },
  {
    id: "c41",
    name: "Ritual Arcano",
    attrs: ["ins", "wlp", "dex"],
    desc: "Canalizar magias antigas e imprevisíveis, desenhando selos perfeitos enquanto luta para manter a própria sanidade.",
  },
  {
    id: "c42",
    name: "Desarme Crítico",
    attrs: ["dex", "ins", "wlp"],
    desc: "Desativar uma bomba ou reator complexo com mãos firmes, desarmar um ataque fatal iminente, dedução lógica veloz e nervos de aço sob extrema pressão.",
  },
  {
    id: "c43",
    name: "Fuga",
    attrs: ["dex", "ins", "mig"],
    desc: "Correr por ruínas em colapso total: saltar destroços, ler o ambiente caindo aos pedaços e não perder o fôlego.",
  },
  {
    id: "c44",
    name: "Segurar os Portões",
    attrs: ["mig", "mig", "wlp"],
    desc: "Feito insano de resistência: usar o próprio corpo para segurar o avanço de uma horda ou impedir que um teto desabe sobre os aliados.",
  },
  {
    id: "c45",
    name: "Cirurgia Milagrosa",
    attrs: ["dex", "ins", "wlp"],
    desc: "Salvar um aliado à beira da morte em pleno campo de batalha, exigindo mãos cirúrgicas, genialidade médica e foco ignorando o caos.",
  },
  {
    id: "c46",
    name: "Discurso da Virada",
    attrs: ["wlp", "wlp", "ins"],
    desc: "Inspirar um exército à beira da derrota, lendo os corações das tropas e projetando sua voz com liderança incontestável.",
  },
  {
    id: "c47",
    name: "Resistir à Corrupção",
    attrs: ["wlp", "wlp", "mig"],
    desc: "Lutar com a mente e o corpo simultaneamente contra uma possessão demoníaca ou toxina mágica letal no sangue.",
  },
  {
    id: "c48",
    name: "Ataque Desesperado",
    attrs: ["mig", "dex", "wlp"],
    desc: "Desferir um único golpe usando absolutamente tudo o que tem: força bruta, precisão letal e a pura força de vontade para vencer.",
  },
  {
    id: "c49",
    name: "Milagre",
    attrs: ["wlp", "wlp", "ins", "ins"],
    desc: "Realizar um feito impossível com auxilio do roteiro.",
  },
  {
    id: "c50",
    name: "Forjar Relíquia Mítica",
    attrs: ["dex", "dex", "ins", "wlp"],
    desc: "Semanas de trabalho ininterrupto combinando técnica perfeita, alta compreensão mágica e dedicação cega para criar um item lendário.",
  },
  {
    id: "c51",
    name: "Sobrevivência Impossível",
    attrs: ["mig", "mig", "wlp", "ins"],
    desc: "Atravessar uma Anomalia Geográfica (como uma Nevasca Eterna ou Deserto de Fogo) liderando o grupo e ignorando a dor extrema.",
  },
  {
    id: "c52",
    name: "Comandar o Fim do Mundo",
    attrs: ["ins", "ins", "wlp", "wlp"],
    desc: "Orquestrar a Grande Tática contra uma ameaça colossal: prever os movimentos do inimigo e coordenar continentes inteiros mentalmente.",
  },
  {
    id: "c53",
    name: "Limit Break: Omnigolpe",
    attrs: ["mig", "dex", "ins", "wlp"],
    desc: "Atingir o ápice do seu ser. Uma ação explosiva e perfeita que une a Força (Mig), a Agilidade (Dex), a Leitura do Inimigo (Ins) e o Espírito (Wlp).",
  },
  {
    id: "c54",
    name: "Dança da Enganação Perfeita",
    attrs: ["dex", "dex", "wlp", "ins"],
    desc: "Convencer a corte inteira ou enganar uma criatura onisciente, combinando linguagem corporal impecável, mentiras complexas e audácia.",
  },
  {
    id: "c55",
    name: "Controle de Multidões",
    attrs: ["wlp", "wlp", "ins"],
    desc: "Acalmar um tumulto violento ou guiar uma multidão em pânico em meio a um desastre, usando presença imponente e leitura rápida da situação.",
  },
  {
    id: "c56",
    name: "Interceptação Perigosa",
    attrs: ["dex", "mig", "ins"],
    desc: "Perseguir e alcançar um alvo em alta velocidade através de um ambiente hostil, combinando reflexos rápidos, explosão física e leitura do terreno.",
  },
  {
    id: "c57",
    name: "Improviso Genial",
    attrs: ["ins", "ins", "dex"],
    desc: "Construir um dispositivo de emergência ou sintetizar um antídoto em poucos segundos usando apenas sucata e materiais instáveis sob extrema pressão.",
  },
  {
    id: "c58",
    name: "Infiltração Impossível",
    attrs: ["dex", "dex", "ins"],
    desc: "Atravessar uma rede de segurança milimetricamente, controlando a respiração e os nervos enquanto lida com patrulhas em tempo real.",
  },
  {
    id: "c59",
    name: "Leitura de comportamento",
    attrs: ["ins", "wlp", "wlp"],
    desc: "Ler expressões faciais e movimentos do corpo com o intuito de entender as emoções dos outros.",
  },
  {
    id: "c60",
    name: "Raciocinio Lógico",
    attrs: ["ins", "ins", "wlp"],
    desc: "Fazer deduções e chegar a conclusões com base em informações obtidas em um tempo recente.",
  },
  {
    id: "c61",
    name: "Iniciativa",
    attrs: ["dex", "dex", "wlp"],
    desc: "Realizar um movimento ou ação mais rápido do que outros.",
  },
  {
    id: "c62",
    name: "Envenenamento",
    attrs: ["ins", "wlp", "dex"],
    desc: "Criar, produzir e/ou aplicar venenos e toxinas.",
  },
  {
    id: "c63",
    name: "Imobilização",
    attrs: ["mig", "wlp", "dex"],
    desc: "Imobilizar, agarrar ou incapacitar usando força pura.",
  },
]

export const QTE_CHECKS = [
  ...ATTRIBUTES.map((a:any) => ({
    id: a,
    name: a.toUpperCase(),
    attrs: [a],
    desc: "Teste de atributo",
  })),
  ...PRESET_CHECKS,
]
